algoritmo "exercicio 02"
// Função : Escrever nome, idade e salario
// Autor : Giovanna Carvalho
// Data : 07/03/2022
// Seção de Declarações 
var
nome:caracter
idade:inteiro
salario:real
inicio
// Seção de Comandos
escreval("Digite seu nome: ")
leia(nome)
escreval("Digite sua idade:")
leia(idade)
escreval("Digite seu salário:")
leia(salario)

escreval("Seu nome é: ",nome)
escreval("Sua idade é: ",idade)
escreval("Seu salário é: ",salario)

 
fimalgoritmo
