algoritmo "exercicio 03"
// Função : Calcular area de um triangulo
// Autor : Giovanna Carvalho
// Data : 14/03/2022
// Seção de Declarações 
var
base,altura,area: real
inicio
// Seção de Comandos 
escreval ("Digite o valor da base: ")
leia(base)
escreval ("Digite o valor da altura: ")
leia(altura)

escreval ("O valor da base é: ",base)
escreval ("O valor da altura é: ",altura)

area <- ((base*altura) /2)

escreval ("O valor total da área é de: ",area)

fimalgoritmo
