algoritmo "Exercicio 03 de programaçoes de algoritmos"
// Função : escreva um algoritmo para ler um valor (do teclado)
// e escrever (na tela) o seu antecessor
// Autor : Giovanna Carvalho
// Data : 21/03/2022
// Seção de Declarações 
var
valor: inteiro
antecessor: inteiro

inicio
// Seção de Comandos 
escreval ("Digite um número:")
leia (valor)

antecessor <- valor - 1
escreval ("O seu antecessor é: ", antecessor)
fimalgoritmo
