algoritmo "conversao_horas"
// Função : Comverter os minutos em horas
// Autor : Giovanna Carvalho
// Data : 09/05/2022
// Seção de Declarações 
var
hora, min, total: real
inicio
// Dados de Entrada
escreval ("Digite as horas:")
leia(hora)
escreval ("Digite os minustos")
leia(min)
// Processamento
total <- (min / 60) + hora
// Dados de Saida
escreval ("O valor convertido em horas é:", total)
fimalgoritmo
